### ISSUE TITLE
P-values from featscore.test

### ISSUE THREAD

**Issue by MohamedRefaat92** [jpiironen/dimreduce#1]
Hi,

First of all thanks for this really handy package! I'm sure I'm going to rely on it in my future projects.

I have a question regarding the P-values of featurescore.test. Isn't it necessary to adjust it for multiple testing?

Best,
Mohamed

**Comment by jpiironen** [comment]
Hi. It depends on what you're doing. If you're only interested in reducing the number of features for purposes of constructing a predictive model using fewer features, then it is usually not necessary to do any multiple testing adjustments. The repository's main page lists a few papers, all of which use feature screening successfully in slightly different ways (no adjustments). The reason is that for prediction it does not matter so much if some irrelevant features happen to survive the screening.

In case you are interested only detecting which features are truly relevant, and false discoveries matter, then you of course need to make adjustments, and there's a large literature on that. But that is not really the purpose of this package

**Comment by jpiironen** [comment]
Closing this issue now.
